version: '3'

services:
  db:
    image: 'mysql:5.7'
    platform: linux/amd64
    environment:
      - 'MYSQL_ROOT_PASSWORD=toor'
      - 'MYSQL_DATABASE=carsfleet'
      - 'MYSQL_USER=carsfleet'
      - 'MYSQL_PASSWORD=carsfleet'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql:rw
    networks:
      - carsfleet-saas

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: toor
    networks:
      - carsfleet-saas

  www:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./docker/web/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - carsfleet-saas

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - carsfleet-saas

  node:
    image: node:lts-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
    tty: true
    networks:
      - carsfleet-saas

networks:
  carsfleet-saas:
    driver: bridge

volumes:
  db-data: